version: '3.8'
networks:
    jenkins-network:
        name: jenkins
services:
    dind:
        container_name: jenkins-docker-in-docker
        image: docker:dind
        privileged: true
        restart: unless-stopped
        networks:
            jenkins-network:
                aliases:
                    - docker
        volumes:
            - ./jenkins/jenkins-docker-certs:/certs/client
            - ./jenkins/jenkins-data:/var/jenkins_home
        environment:
            - DOCKER_TLS_CERTDIR=/certs

    jenkins:
        container_name: jenkins-blueocean
        restart: unless-stopped
        build:
            context: ./jenkins
        networks:
            - jenkins-network
        ports:
            - 8082:8080
            - 50002:50000
        volumes:
            - ./jenkins/jenkins-docker-certs:/certs/client
            - ./jenkins/jenkins-data:/var/jenkins_home
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
            - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
#            - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
        secrets:
            - jenkins_admin_password
#        env_file:
#            - .env
    nginx:
        build:
            context: ./nginx
        container_name: jenkins-nginx
        networks:
            - jenkins-network
        ports:
            - 443:443
        volumes:
            - ./nginx/app.conf.nginx:/etc/nginx/conf.d/default.conf
            - ./nginx/log:/app/log
        depends_on:
            - jenkins
        restart: unless-stopped
secrets:
    jenkins_admin_password:
        file: ./secrets/JENKINS_ADMIN_PASSWORD
